// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package servicepostgressqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ServiceQueueRecord struct {
	SubmissionID   string
	QueueOrder     int64
	MatchID        string
	ParentRunID    pgtype.Text
	RunKind        string
	Official       bool
	GameID         string
	GameVersion    string
	RulesetVersion string
	PlayersJson    []byte
	OutputDir      string
	AttemptCount   int32
	State          string
	WorkerID       pgtype.Text
	TerminalJson   []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
