// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package servicepostgressqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AccountIdentity struct {
	IdentityID      pgtype.UUID
	AccountID       pgtype.UUID
	Provider        string
	ProviderSubject string
	ProviderLogin   string
	ProviderEmail   pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AccountRole struct {
	AccountID pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type AccountSession struct {
	SessionID        pgtype.UUID
	AccountID        pgtype.UUID
	SessionTokenHash string
	ExpiresAt        pgtype.Timestamptz
	LastSeenAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type AiBot struct {
	BotID              pgtype.UUID
	OwnerAccountID     pgtype.UUID
	ScopeID            string
	BotName            string
	NormalizedBotName  string
	LifecycleState     string
	ActiveSubmissionID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	RetiredAt          pgtype.Timestamptz
}

type AiSubmissionRevision struct {
	AiSubmissionID  pgtype.UUID
	BotID           pgtype.UUID
	ArtifactID      string
	RuntimeKind     string
	AiID            string
	ValidationState string
	CreatedAt       pgtype.Timestamptz
}

type CompetitionScope struct {
	ScopeID               string
	GameID                string
	GameVersionMajor      int32
	RulesetVersion        string
	ActiveReleaseID       pgtype.UUID
	PlayerCount           int32
	MaxActiveBotsPerOwner int32
	CreatedAt             pgtype.Timestamptz
}

type GameRelease struct {
	ReleaseID         pgtype.UUID
	GameID            string
	GameVersion       string
	ArtifactID        string
	BuildMode         string
	BuilderID         string
	SupportedRulesets []byte
	Source            string
	SourceID          string
	CreatedAt         pgtype.Timestamptz
}

type ServiceQueueRecord struct {
	SubmissionID    string
	QueueOrder      int64
	MatchID         string
	ParentRunID     pgtype.Text
	RunKind         string
	Official        bool
	GameID          string
	GameVersion     string
	RulesetVersion  string
	PlayersJson     []byte
	OutputDir       string
	AttemptCount    int32
	State           string
	WorkerID        pgtype.Text
	LeaseDeadline   pgtype.Timestamptz
	LastHeartbeatAt pgtype.Timestamptz
	TerminalJson    []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type SignupInvite struct {
	InviteID         pgtype.UUID
	InviteTokenHash  string
	Role             string
	ExpiresAt        pgtype.Timestamptz
	ClaimedAccountID pgtype.UUID
	ClaimedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}
