// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: query.sql

package servicepostgressqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelQueueRecord = `-- name: CancelQueueRecord :exec
UPDATE service_queue_records
SET state = $1, worker_id = NULL, terminal_json = NULL, updated_at = NOW()
WHERE submission_id = $2
`

type CancelQueueRecordParams struct {
	State        string
	SubmissionID string
}

func (q *Queries) CancelQueueRecord(ctx context.Context, arg CancelQueueRecordParams) error {
	_, err := q.db.Exec(ctx, cancelQueueRecord, arg.State, arg.SubmissionID)
	return err
}

const claimNextQueueRecord = `-- name: ClaimNextQueueRecord :one
WITH next_record AS (
    SELECT submission_id
    FROM service_queue_records
    WHERE service_queue_records.state = $3
    ORDER BY queue_order
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE service_queue_records AS records
SET state = $1, worker_id = $2, updated_at = NOW()
FROM next_record
WHERE records.submission_id = next_record.submission_id
RETURNING
    records.submission_id,
    records.match_id,
    records.parent_run_id,
    records.run_kind,
    records.official,
    records.game_id,
    records.game_version,
    records.ruleset_version,
    records.players_json,
    records.output_dir,
    records.attempt_count,
    records.state,
    records.worker_id,
    records.terminal_json
`

type ClaimNextQueueRecordParams struct {
	LeasedState string
	WorkerID    pgtype.Text
	QueuedState string
}

type ClaimNextQueueRecordRow struct {
	SubmissionID   string
	MatchID        string
	ParentRunID    pgtype.Text
	RunKind        string
	Official       bool
	GameID         string
	GameVersion    string
	RulesetVersion string
	PlayersJson    []byte
	OutputDir      string
	AttemptCount   int32
	State          string
	WorkerID       pgtype.Text
	TerminalJson   []byte
}

func (q *Queries) ClaimNextQueueRecord(ctx context.Context, arg ClaimNextQueueRecordParams) (ClaimNextQueueRecordRow, error) {
	row := q.db.QueryRow(ctx, claimNextQueueRecord, arg.LeasedState, arg.WorkerID, arg.QueuedState)
	var i ClaimNextQueueRecordRow
	err := row.Scan(
		&i.SubmissionID,
		&i.MatchID,
		&i.ParentRunID,
		&i.RunKind,
		&i.Official,
		&i.GameID,
		&i.GameVersion,
		&i.RulesetVersion,
		&i.PlayersJson,
		&i.OutputDir,
		&i.AttemptCount,
		&i.State,
		&i.WorkerID,
		&i.TerminalJson,
	)
	return i, err
}

const createQueueRecord = `-- name: CreateQueueRecord :exec
INSERT INTO service_queue_records (
    submission_id,
    match_id,
    parent_run_id,
    run_kind,
    official,
    game_id,
    game_version,
    ruleset_version,
    players_json,
    output_dir,
    attempt_count,
    state
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type CreateQueueRecordParams struct {
	SubmissionID   string
	MatchID        string
	ParentRunID    pgtype.Text
	RunKind        string
	Official       bool
	GameID         string
	GameVersion    string
	RulesetVersion string
	PlayersJson    []byte
	OutputDir      string
	AttemptCount   int32
	State          string
}

func (q *Queries) CreateQueueRecord(ctx context.Context, arg CreateQueueRecordParams) error {
	_, err := q.db.Exec(ctx, createQueueRecord,
		arg.SubmissionID,
		arg.MatchID,
		arg.ParentRunID,
		arg.RunKind,
		arg.Official,
		arg.GameID,
		arg.GameVersion,
		arg.RulesetVersion,
		arg.PlayersJson,
		arg.OutputDir,
		arg.AttemptCount,
		arg.State,
	)
	return err
}

const getQueueRecord = `-- name: GetQueueRecord :one
SELECT
    submission_id,
    match_id,
    parent_run_id,
    run_kind,
    official,
    game_id,
    game_version,
    ruleset_version,
    players_json,
    output_dir,
    attempt_count,
    state,
    worker_id,
    terminal_json
FROM service_queue_records
WHERE submission_id = $1
`

type GetQueueRecordRow struct {
	SubmissionID   string
	MatchID        string
	ParentRunID    pgtype.Text
	RunKind        string
	Official       bool
	GameID         string
	GameVersion    string
	RulesetVersion string
	PlayersJson    []byte
	OutputDir      string
	AttemptCount   int32
	State          string
	WorkerID       pgtype.Text
	TerminalJson   []byte
}

func (q *Queries) GetQueueRecord(ctx context.Context, submissionID string) (GetQueueRecordRow, error) {
	row := q.db.QueryRow(ctx, getQueueRecord, submissionID)
	var i GetQueueRecordRow
	err := row.Scan(
		&i.SubmissionID,
		&i.MatchID,
		&i.ParentRunID,
		&i.RunKind,
		&i.Official,
		&i.GameID,
		&i.GameVersion,
		&i.RulesetVersion,
		&i.PlayersJson,
		&i.OutputDir,
		&i.AttemptCount,
		&i.State,
		&i.WorkerID,
		&i.TerminalJson,
	)
	return i, err
}

const getQueueRecordForUpdate = `-- name: GetQueueRecordForUpdate :one
SELECT
    submission_id,
    match_id,
    parent_run_id,
    run_kind,
    official,
    game_id,
    game_version,
    ruleset_version,
    players_json,
    output_dir,
    attempt_count,
    state,
    worker_id,
    terminal_json
FROM service_queue_records
WHERE submission_id = $1
FOR UPDATE
`

type GetQueueRecordForUpdateRow struct {
	SubmissionID   string
	MatchID        string
	ParentRunID    pgtype.Text
	RunKind        string
	Official       bool
	GameID         string
	GameVersion    string
	RulesetVersion string
	PlayersJson    []byte
	OutputDir      string
	AttemptCount   int32
	State          string
	WorkerID       pgtype.Text
	TerminalJson   []byte
}

func (q *Queries) GetQueueRecordForUpdate(ctx context.Context, submissionID string) (GetQueueRecordForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getQueueRecordForUpdate, submissionID)
	var i GetQueueRecordForUpdateRow
	err := row.Scan(
		&i.SubmissionID,
		&i.MatchID,
		&i.ParentRunID,
		&i.RunKind,
		&i.Official,
		&i.GameID,
		&i.GameVersion,
		&i.RulesetVersion,
		&i.PlayersJson,
		&i.OutputDir,
		&i.AttemptCount,
		&i.State,
		&i.WorkerID,
		&i.TerminalJson,
	)
	return i, err
}

const listQueueRecords = `-- name: ListQueueRecords :many
SELECT
    submission_id,
    match_id,
    parent_run_id,
    run_kind,
    official,
    game_id,
    game_version,
    ruleset_version,
    players_json,
    output_dir,
    attempt_count,
    state,
    worker_id,
    terminal_json
FROM service_queue_records
ORDER BY queue_order
`

type ListQueueRecordsRow struct {
	SubmissionID   string
	MatchID        string
	ParentRunID    pgtype.Text
	RunKind        string
	Official       bool
	GameID         string
	GameVersion    string
	RulesetVersion string
	PlayersJson    []byte
	OutputDir      string
	AttemptCount   int32
	State          string
	WorkerID       pgtype.Text
	TerminalJson   []byte
}

func (q *Queries) ListQueueRecords(ctx context.Context) ([]ListQueueRecordsRow, error) {
	rows, err := q.db.Query(ctx, listQueueRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQueueRecordsRow
	for rows.Next() {
		var i ListQueueRecordsRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.MatchID,
			&i.ParentRunID,
			&i.RunKind,
			&i.Official,
			&i.GameID,
			&i.GameVersion,
			&i.RulesetVersion,
			&i.PlayersJson,
			&i.OutputDir,
			&i.AttemptCount,
			&i.State,
			&i.WorkerID,
			&i.TerminalJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQueueRecord = `-- name: UpdateQueueRecord :exec
UPDATE service_queue_records
SET
    match_id = $1,
    parent_run_id = $2,
    run_kind = $3,
    official = $4,
    game_id = $5,
    game_version = $6,
    ruleset_version = $7,
    players_json = $8,
    output_dir = $9,
    attempt_count = $10,
    state = $11,
    worker_id = $12,
    terminal_json = $13,
    updated_at = NOW()
WHERE submission_id = $14
`

type UpdateQueueRecordParams struct {
	MatchID        string
	ParentRunID    pgtype.Text
	RunKind        string
	Official       bool
	GameID         string
	GameVersion    string
	RulesetVersion string
	PlayersJson    []byte
	OutputDir      string
	AttemptCount   int32
	State          string
	WorkerID       pgtype.Text
	TerminalJson   []byte
	SubmissionID   string
}

func (q *Queries) UpdateQueueRecord(ctx context.Context, arg UpdateQueueRecordParams) error {
	_, err := q.db.Exec(ctx, updateQueueRecord,
		arg.MatchID,
		arg.ParentRunID,
		arg.RunKind,
		arg.Official,
		arg.GameID,
		arg.GameVersion,
		arg.RulesetVersion,
		arg.PlayersJson,
		arg.OutputDir,
		arg.AttemptCount,
		arg.State,
		arg.WorkerID,
		arg.TerminalJson,
		arg.SubmissionID,
	)
	return err
}
