// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: query.sql

package servicepostgressqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelQueueRecord = `-- name: CancelQueueRecord :exec
UPDATE service_queue_records
SET state = $1, worker_id = NULL, lease_deadline = NULL, last_heartbeat_at = NULL, terminal_json = NULL, updated_at = NOW()
WHERE submission_id = $2
`

type CancelQueueRecordParams struct {
	State        string
	SubmissionID string
}

func (q *Queries) CancelQueueRecord(ctx context.Context, arg CancelQueueRecordParams) error {
	_, err := q.db.Exec(ctx, cancelQueueRecord, arg.State, arg.SubmissionID)
	return err
}

const claimNextQueueRecord = `-- name: ClaimNextQueueRecord :one
WITH next_record AS (
    SELECT submission_id
    FROM service_queue_records
    WHERE service_queue_records.state = $5
    ORDER BY queue_order
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE service_queue_records AS records
SET state = $1,
    worker_id = $2,
    lease_deadline = $3,
    last_heartbeat_at = $4,
    updated_at = NOW()
FROM next_record
WHERE records.submission_id = next_record.submission_id
RETURNING
    records.submission_id,
    records.match_id,
    records.parent_run_id,
    records.run_kind,
    records.official,
    records.game_id,
    records.game_version,
    records.ruleset_version,
    records.players_json,
    records.output_dir,
    records.attempt_count,
    records.state,
    records.worker_id,
    records.lease_deadline,
    records.last_heartbeat_at,
    records.terminal_json
`

type ClaimNextQueueRecordParams struct {
	LeasedState     string
	WorkerID        pgtype.Text
	LeaseDeadline   pgtype.Timestamptz
	LastHeartbeatAt pgtype.Timestamptz
	QueuedState     string
}

type ClaimNextQueueRecordRow struct {
	SubmissionID    string
	MatchID         string
	ParentRunID     pgtype.Text
	RunKind         string
	Official        bool
	GameID          string
	GameVersion     string
	RulesetVersion  string
	PlayersJson     []byte
	OutputDir       string
	AttemptCount    int32
	State           string
	WorkerID        pgtype.Text
	LeaseDeadline   pgtype.Timestamptz
	LastHeartbeatAt pgtype.Timestamptz
	TerminalJson    []byte
}

func (q *Queries) ClaimNextQueueRecord(ctx context.Context, arg ClaimNextQueueRecordParams) (ClaimNextQueueRecordRow, error) {
	row := q.db.QueryRow(ctx, claimNextQueueRecord,
		arg.LeasedState,
		arg.WorkerID,
		arg.LeaseDeadline,
		arg.LastHeartbeatAt,
		arg.QueuedState,
	)
	var i ClaimNextQueueRecordRow
	err := row.Scan(
		&i.SubmissionID,
		&i.MatchID,
		&i.ParentRunID,
		&i.RunKind,
		&i.Official,
		&i.GameID,
		&i.GameVersion,
		&i.RulesetVersion,
		&i.PlayersJson,
		&i.OutputDir,
		&i.AttemptCount,
		&i.State,
		&i.WorkerID,
		&i.LeaseDeadline,
		&i.LastHeartbeatAt,
		&i.TerminalJson,
	)
	return i, err
}

const createQueueRecord = `-- name: CreateQueueRecord :exec
INSERT INTO service_queue_records (
    submission_id,
    match_id,
    parent_run_id,
    run_kind,
    official,
    game_id,
    game_version,
    ruleset_version,
    players_json,
    output_dir,
    attempt_count,
    state
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type CreateQueueRecordParams struct {
	SubmissionID   string
	MatchID        string
	ParentRunID    pgtype.Text
	RunKind        string
	Official       bool
	GameID         string
	GameVersion    string
	RulesetVersion string
	PlayersJson    []byte
	OutputDir      string
	AttemptCount   int32
	State          string
}

func (q *Queries) CreateQueueRecord(ctx context.Context, arg CreateQueueRecordParams) error {
	_, err := q.db.Exec(ctx, createQueueRecord,
		arg.SubmissionID,
		arg.MatchID,
		arg.ParentRunID,
		arg.RunKind,
		arg.Official,
		arg.GameID,
		arg.GameVersion,
		arg.RulesetVersion,
		arg.PlayersJson,
		arg.OutputDir,
		arg.AttemptCount,
		arg.State,
	)
	return err
}

const getQueueRecord = `-- name: GetQueueRecord :one
SELECT
    submission_id,
    match_id,
    parent_run_id,
    run_kind,
    official,
    game_id,
    game_version,
    ruleset_version,
    players_json,
    output_dir,
    attempt_count,
    state,
    worker_id,
    lease_deadline,
    last_heartbeat_at,
    terminal_json
FROM service_queue_records
WHERE submission_id = $1
`

type GetQueueRecordRow struct {
	SubmissionID    string
	MatchID         string
	ParentRunID     pgtype.Text
	RunKind         string
	Official        bool
	GameID          string
	GameVersion     string
	RulesetVersion  string
	PlayersJson     []byte
	OutputDir       string
	AttemptCount    int32
	State           string
	WorkerID        pgtype.Text
	LeaseDeadline   pgtype.Timestamptz
	LastHeartbeatAt pgtype.Timestamptz
	TerminalJson    []byte
}

func (q *Queries) GetQueueRecord(ctx context.Context, submissionID string) (GetQueueRecordRow, error) {
	row := q.db.QueryRow(ctx, getQueueRecord, submissionID)
	var i GetQueueRecordRow
	err := row.Scan(
		&i.SubmissionID,
		&i.MatchID,
		&i.ParentRunID,
		&i.RunKind,
		&i.Official,
		&i.GameID,
		&i.GameVersion,
		&i.RulesetVersion,
		&i.PlayersJson,
		&i.OutputDir,
		&i.AttemptCount,
		&i.State,
		&i.WorkerID,
		&i.LeaseDeadline,
		&i.LastHeartbeatAt,
		&i.TerminalJson,
	)
	return i, err
}

const getQueueRecordForUpdate = `-- name: GetQueueRecordForUpdate :one
SELECT
    submission_id,
    match_id,
    parent_run_id,
    run_kind,
    official,
    game_id,
    game_version,
    ruleset_version,
    players_json,
    output_dir,
    attempt_count,
    state,
    worker_id,
    lease_deadline,
    last_heartbeat_at,
    terminal_json
FROM service_queue_records
WHERE submission_id = $1
FOR UPDATE
`

type GetQueueRecordForUpdateRow struct {
	SubmissionID    string
	MatchID         string
	ParentRunID     pgtype.Text
	RunKind         string
	Official        bool
	GameID          string
	GameVersion     string
	RulesetVersion  string
	PlayersJson     []byte
	OutputDir       string
	AttemptCount    int32
	State           string
	WorkerID        pgtype.Text
	LeaseDeadline   pgtype.Timestamptz
	LastHeartbeatAt pgtype.Timestamptz
	TerminalJson    []byte
}

func (q *Queries) GetQueueRecordForUpdate(ctx context.Context, submissionID string) (GetQueueRecordForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getQueueRecordForUpdate, submissionID)
	var i GetQueueRecordForUpdateRow
	err := row.Scan(
		&i.SubmissionID,
		&i.MatchID,
		&i.ParentRunID,
		&i.RunKind,
		&i.Official,
		&i.GameID,
		&i.GameVersion,
		&i.RulesetVersion,
		&i.PlayersJson,
		&i.OutputDir,
		&i.AttemptCount,
		&i.State,
		&i.WorkerID,
		&i.LeaseDeadline,
		&i.LastHeartbeatAt,
		&i.TerminalJson,
	)
	return i, err
}

const heartbeatQueueRecord = `-- name: HeartbeatQueueRecord :execrows
UPDATE service_queue_records
SET lease_deadline = $1, last_heartbeat_at = $2, updated_at = NOW()
WHERE submission_id = $3 AND worker_id = $4
  AND state IN ('leased', 'running', 'persisting')
`

type HeartbeatQueueRecordParams struct {
	LeaseDeadline   pgtype.Timestamptz
	LastHeartbeatAt pgtype.Timestamptz
	SubmissionID    string
	WorkerID        pgtype.Text
}

func (q *Queries) HeartbeatQueueRecord(ctx context.Context, arg HeartbeatQueueRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatQueueRecord,
		arg.LeaseDeadline,
		arg.LastHeartbeatAt,
		arg.SubmissionID,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOwnedBots = `-- name: ListOwnedBots :many
SELECT bot_id, owner_account_id, scope_id, bot_name, normalized_bot_name, lifecycle_state, active_submission_id, created_at, retired_at
FROM ai_bots
WHERE owner_account_id = $1 AND scope_id = $2
ORDER BY created_at
`

type ListOwnedBotsParams struct {
	OwnerAccountID pgtype.UUID
	ScopeID        string
}

func (q *Queries) ListOwnedBots(ctx context.Context, arg ListOwnedBotsParams) ([]AiBot, error) {
	rows, err := q.db.Query(ctx, listOwnedBots, arg.OwnerAccountID, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiBot
	for rows.Next() {
		var i AiBot
		if err := rows.Scan(
			&i.BotID,
			&i.OwnerAccountID,
			&i.ScopeID,
			&i.BotName,
			&i.NormalizedBotName,
			&i.LifecycleState,
			&i.ActiveSubmissionID,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueRecords = `-- name: ListQueueRecords :many
SELECT
    submission_id,
    match_id,
    parent_run_id,
    run_kind,
    official,
    game_id,
    game_version,
    ruleset_version,
    players_json,
    output_dir,
    attempt_count,
    state,
    worker_id,
    lease_deadline,
    last_heartbeat_at,
    terminal_json
FROM service_queue_records
ORDER BY queue_order
`

type ListQueueRecordsRow struct {
	SubmissionID    string
	MatchID         string
	ParentRunID     pgtype.Text
	RunKind         string
	Official        bool
	GameID          string
	GameVersion     string
	RulesetVersion  string
	PlayersJson     []byte
	OutputDir       string
	AttemptCount    int32
	State           string
	WorkerID        pgtype.Text
	LeaseDeadline   pgtype.Timestamptz
	LastHeartbeatAt pgtype.Timestamptz
	TerminalJson    []byte
}

func (q *Queries) ListQueueRecords(ctx context.Context) ([]ListQueueRecordsRow, error) {
	rows, err := q.db.Query(ctx, listQueueRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQueueRecordsRow
	for rows.Next() {
		var i ListQueueRecordsRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.MatchID,
			&i.ParentRunID,
			&i.RunKind,
			&i.Official,
			&i.GameID,
			&i.GameVersion,
			&i.RulesetVersion,
			&i.PlayersJson,
			&i.OutputDir,
			&i.AttemptCount,
			&i.State,
			&i.WorkerID,
			&i.LeaseDeadline,
			&i.LastHeartbeatAt,
			&i.TerminalJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionRevisionsForBot = `-- name: ListSubmissionRevisionsForBot :many
SELECT ai_submission_id, bot_id, artifact_id, runtime_kind, ai_id, validation_state, created_at
FROM ai_submission_revisions
WHERE bot_id = $1
ORDER BY created_at
`

func (q *Queries) ListSubmissionRevisionsForBot(ctx context.Context, botID pgtype.UUID) ([]AiSubmissionRevision, error) {
	rows, err := q.db.Query(ctx, listSubmissionRevisionsForBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiSubmissionRevision
	for rows.Next() {
		var i AiSubmissionRevision
		if err := rows.Scan(
			&i.AiSubmissionID,
			&i.BotID,
			&i.ArtifactID,
			&i.RuntimeKind,
			&i.AiID,
			&i.ValidationState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverExpiredQueueRecords = `-- name: RecoverExpiredQueueRecords :execrows
UPDATE service_queue_records
SET state = $1, worker_id = NULL, lease_deadline = NULL, last_heartbeat_at = NULL, updated_at = NOW()
WHERE state IN ('leased', 'running', 'persisting') AND lease_deadline <= $2
`

type RecoverExpiredQueueRecordsParams struct {
	QueuedState string
	Now         pgtype.Timestamptz
}

func (q *Queries) RecoverExpiredQueueRecords(ctx context.Context, arg RecoverExpiredQueueRecordsParams) (int64, error) {
	result, err := q.db.Exec(ctx, recoverExpiredQueueRecords, arg.QueuedState, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateQueueRecord = `-- name: UpdateQueueRecord :exec
UPDATE service_queue_records
SET
    match_id = $1,
    parent_run_id = $2,
    run_kind = $3,
    official = $4,
    game_id = $5,
    game_version = $6,
    ruleset_version = $7,
    players_json = $8,
    output_dir = $9,
    attempt_count = $10,
    state = $11,
    worker_id = $12,
    lease_deadline = $13,
    last_heartbeat_at = $14,
    terminal_json = $15,
    updated_at = NOW()
WHERE submission_id = $16
`

type UpdateQueueRecordParams struct {
	MatchID         string
	ParentRunID     pgtype.Text
	RunKind         string
	Official        bool
	GameID          string
	GameVersion     string
	RulesetVersion  string
	PlayersJson     []byte
	OutputDir       string
	AttemptCount    int32
	State           string
	WorkerID        pgtype.Text
	LeaseDeadline   pgtype.Timestamptz
	LastHeartbeatAt pgtype.Timestamptz
	TerminalJson    []byte
	SubmissionID    string
}

func (q *Queries) UpdateQueueRecord(ctx context.Context, arg UpdateQueueRecordParams) error {
	_, err := q.db.Exec(ctx, updateQueueRecord,
		arg.MatchID,
		arg.ParentRunID,
		arg.RunKind,
		arg.Official,
		arg.GameID,
		arg.GameVersion,
		arg.RulesetVersion,
		arg.PlayersJson,
		arg.OutputDir,
		arg.AttemptCount,
		arg.State,
		arg.WorkerID,
		arg.LeaseDeadline,
		arg.LastHeartbeatAt,
		arg.TerminalJson,
		arg.SubmissionID,
	)
	return err
}
